name: Build dae for Android

on:
  workflow_dispatch:
  push:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: daeuniverse/dae
          submodules: recursive
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          check-latest: true

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm make git

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.6.0
        id: setup-ndk
        with:
          ndk-version: r29-beta1
          check-latest: true

      - name: Build dae
        run: |
          TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          
          export CLANG=$TOOLCHAIN/aarch64-linux-android35-clang
          export CC=$TOOLCHAIN/aarch64-linux-android35-clang
          export STRIP=$TOOLCHAIN/llvm-strip
          
          export CGO_ENABLED=1
          export CGO_CFLAGS="-Wno-error=incompatible-pointer-types"
          export CGO_LDFLAGS="-Wl,-z,max-page-size=16384"
          
          make GOOS=android \
               GOARCH=arm64 \
               CLANG=$CLANG \
               STRIP=$STRIP \
               GOFLAGS="-buildvcs=false" \
               BUILD_ARGS="-ldflags='-s -w -extldflags=-zmax-page-size=16384'" \
               dae

      - name: Upload dae Binary
        uses: actions/upload-artifact@v4
        with:
          name: dae-android15-arm64
          path: dae
